ARG APP_DOCKER_IMAGE
FROM ${APP_DOCKER_IMAGE} AS build
ARG COMPOSER_AUTH
WORKDIR /getoken_code
COPY ./composer.json ./composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction --no-progress --prefer-dist --no-scripts --no-ansi

FROM ${APP_DOCKER_IMAGE}
COPY --chown=www-data:www-data --from=build /getoken_code .
COPY --chown=www-data:www-data . .
RUN composer run post-autoload-dump && find ./ -type d -exec chmod 755 {} + && chown -R www-data.www-data /getoken_code
